clear

countires = {...
    'Poland';...
    'Spain';...
    'Belgium';...
    'Bulgaria';...
    'Slovenia';...
    'United Kingdom';...
    'Austria';...
    'Netherlands';...
    'Portugal';...
    'France';...
    'Malta';...
    'Latvia';...
    'Sweden';...
    'Hungary';...
    'Estonia';...
    'Finland';...
    'Lithuania';...
    'Denmark';...
    'Cyprus';...
    'Norway';...
    'Iceland';...
    };

deaths = {};

i = 1;
for c = countires'
    cell2mat(c)
    ctry = Country(cell2mat(c));
    countires{i,2} = 1000000*sum(ctry.deaths(ctry.dates<datetime("2021-12-31"))/ctry.population)
    i=i+1;
end

sortrows(countires,2,'descend')

% plot(c1.dates(c1.dates<datetime("2020-12-31")),c1.deaths(c1.dates<datetime("2020-12-31"))/c1.population)

